version: '3.8'

services:
  langgraph-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_VERSION: ${APP_VERSION:-1.0.0}
    image: ${IMAGE_NAME:-biasoo/langgraph-api}:${APP_VERSION:-1.0.0}
    container_name: langgraph-api
    ports:
      - "0.0.0.0:8000:8000"
    environment:
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_API_BASE=${OPENAI_API_BASE:-}
    volumes:
      - ./config:/app/config:ro
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

