CREATE TABLE `sale_amazon_order` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `amazon_order_id` varchar(50) DEFAULT NULL COMMENT '亚马逊订单号',
  `seller_order_id` varchar(50) DEFAULT NULL COMMENT '销售订单号',
  `purchase_date` varchar(50) DEFAULT NULL COMMENT '购买日期',
  `last_update_date` varchar(50) DEFAULT NULL COMMENT '最近更新日期',
  `order_status` varchar(20) DEFAULT NULL COMMENT '订单状态',
  `fulfillment_channel` varchar(20) DEFAULT NULL COMMENT '配送渠道',
  `sales_channel` varchar(50) DEFAULT NULL COMMENT '销售渠道',
  `order_channel` varchar(50) DEFAULT NULL COMMENT '订单渠道',
  `ship_service_level` varchar(50) DEFAULT NULL COMMENT '运输服务级别',
  `currency_code` varchar(50) DEFAULT NULL COMMENT '币种',
  `amount` varchar(20) DEFAULT NULL COMMENT '总金额',
  `number_of_items_shipped` int(11) DEFAULT NULL COMMENT '已发货数量',
  `number_of_items_unshipped` int(11) DEFAULT NULL COMMENT '未发货数量',
  `payment_method` varchar(64) DEFAULT NULL COMMENT '付款方式',
  `marketplace_id` varchar(20) DEFAULT NULL COMMENT '市场ID',
  `shipment_service_level_category` varchar(50) DEFAULT NULL COMMENT '运输服务类别',
  `easy_ship_shipment_status` varchar(50) DEFAULT NULL COMMENT '发货状态',
  `cba_displayable_shipping_label` varchar(50) DEFAULT NULL COMMENT '运输标签',
  `order_type` varchar(50) DEFAULT NULL COMMENT '订单类型',
  `earliest_ship_date` varchar(50) DEFAULT NULL COMMENT '最早发货日期',
  `latest_ship_date` varchar(50) DEFAULT NULL COMMENT '最迟发货日期',
  `earliest_delivery_date` varchar(50) DEFAULT NULL COMMENT '最早交货日期',
  `latest_delivery_date` varchar(50) DEFAULT NULL COMMENT '最迟交货日期',
  `is_business_order` varchar(20) DEFAULT NULL COMMENT '是否商业订单',
  `is_prime` varchar(20) DEFAULT NULL COMMENT '是否卖家配送',
  `is_premium_order` varchar(20) DEFAULT NULL COMMENT '是否优先',
  `is_global_express_enabled` varchar(20) DEFAULT NULL COMMENT 'isGlobalExpressEnabled',
  `replaced_order_id` varchar(50) DEFAULT NULL COMMENT '替换订单号',
  `is_replacement_order` varchar(20) DEFAULT NULL COMMENT '是否为替换订单',
  `promise_response_due_date` varchar(50) DEFAULT NULL COMMENT '承诺预计发货日期',
  `is_estimated_ship_date_set` varchar(50) DEFAULT NULL COMMENT '是否预计发货日期',
  `is_sold_by_ab` varchar(20) DEFAULT NULL COMMENT 'isIsSoldByAB',
  `buyer_name` varchar(100) DEFAULT NULL COMMENT '买家名称',
  `buyer_email` varchar(100) DEFAULT NULL COMMENT '买家邮箱',
  `sync_items` varchar(20) DEFAULT NULL COMMENT '同步商品信息',
  `sync_buyer_info` varchar(20) DEFAULT NULL COMMENT '同步买家信息',
  `sync_address` varchar(20) DEFAULT NULL COMMENT '同步地址信息',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  `shop_id` bigint(20) DEFAULT NULL COMMENT '店铺id',
  `account` varchar(16) DEFAULT NULL COMMENT '账号',
  `site` varchar(16) DEFAULT NULL COMMENT '站点',
  `refund_flag` varchar(5) DEFAULT 'N' COMMENT '退款标识',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_order_status` (`order_status`) USING BTREE,
  KEY `idx_order_id` (`amazon_order_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=4231856 DEFAULT CHARSET=utf8mb4 COMMENT='亚马逊订单表';

CREATE TABLE `sale_amazon_order_item` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `amazon_order_id` varchar(50) DEFAULT NULL COMMENT '亚马逊订单号',
  `asin` varchar(50) DEFAULT NULL COMMENT 'ASIN',
  `seller_sku` varchar(100) DEFAULT NULL COMMENT '亚马逊SKU',
  `order_item_id` varchar(50) DEFAULT NULL COMMENT '订单商品ID',
  `title` varchar(500) DEFAULT NULL COMMENT '标题',
  `quantity_ordered` int(11) DEFAULT NULL COMMENT '下单数量',
  `quantity_shipped` int(11) DEFAULT NULL COMMENT '已发货数量',
  `number_of_items` int(11) DEFAULT NULL COMMENT '商品数量',
  `item_price` varchar(20) DEFAULT NULL COMMENT '商品价格',
  `shipping_price` varchar(20) DEFAULT NULL COMMENT '配送价格',
  `item_tax` varchar(20) DEFAULT NULL COMMENT '商品价格税',
  `shipping_tax` varchar(20) DEFAULT NULL COMMENT '配送价格税',
  `shipping_discount` varchar(20) DEFAULT NULL COMMENT '配送折扣',
  `shipping_discount_tax` varchar(20) DEFAULT NULL COMMENT '配送折扣税',
  `promotion_discount` varchar(20) DEFAULT NULL COMMENT '促销折扣',
  `promotion_discount_tax` varchar(20) DEFAULT NULL COMMENT '促销折扣税',
  `fba_unit_fulfillment_fee` varchar(255) DEFAULT NULL COMMENT 'fba运费',
  `refund_commission_fee` varchar(255) DEFAULT NULL COMMENT '退款手续费',
  `sales_commission` varchar(255) DEFAULT NULL COMMENT '销售佣金',
  `refund_amount` varchar(255) DEFAULT NULL COMMENT '退款金额',
  `promotion_ids` varchar(500) DEFAULT NULL COMMENT '促销ID',
  `cod_fee` varchar(20) DEFAULT NULL COMMENT 'COD费用',
  `cod_fee_discount` varchar(20) DEFAULT NULL COMMENT 'COD折扣',
  `is_gift` varchar(20) DEFAULT NULL COMMENT '是否礼品',
  `is_transparency` varchar(20) DEFAULT NULL COMMENT '透明度',
  `ioss_number` varchar(50) DEFAULT NULL COMMENT 'IOSS号',
  `deemed_reseller_category` varchar(20) DEFAULT NULL COMMENT '经销商类别',
  `shop_id` bigint(20) DEFAULT NULL COMMENT '店铺ID',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  `account` varchar(16) DEFAULT NULL COMMENT '账号',
  `site` varchar(16) DEFAULT NULL COMMENT '站点',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_site_asin` (`site`,`asin`) USING BTREE,
  KEY `idx_order_id` (`amazon_order_id`) USING BTREE,
  KEY `sale_amazon_order_item_seller_sku_IDX` (`seller_sku`) USING BTREE,
  KEY `sale_amazon_order_item_order_item_id_IDX` (`order_item_id`) USING BTREE,
  KEY `sale_amazon_order_item_shop_id_IDX` (`shop_id`,`account`,`site`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=4034003 DEFAULT CHARSET=utf8mb4 COMMENT='亚马逊订单商品表';

